<a href="https://colab.research.google.com/github/Nikhil-gitub/23CSBTB27_PDS/blob/main/Lab03_PDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([10, 20, 30])

print("2D Array A:\n", A)
print("1D Array B:\n", B)


C = A + B
print("A + B (Broadcasting result):\n", C)
print("Shape of A:", A.shape, "Shape of B:", B.shape, "Shape of Result:", C.shape)


X = np.arange(12).reshape(2,2,3)
print("3D Array X:\n", X)

scalar = 5
Y = X + scalar
print("X + scalar (5):\n", Y)
print("Shape of X:", X.shape, "Shape of scalar: ()", "Result Shape:", Y.shape)


D = np.array([1, 2])
print("Array D:", D, "Shape:", D.shape)


D_reshaped = D[:, np.newaxis]
print("Reshaped D:\n", D_reshaped, "Shape:", D_reshaped.shape)

E = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Array E:\n", E, "Shape:", E.shape)

F = D_reshaped + E
print("Broadcasted (D reshaped + E):\n", F)
print("Shapes: D_reshaped:", D_reshaped.shape, "E:", E.shape, "Result:", F.shape)


G = np.array([1, 2, 3, 4])

try:
    invalid = A + G
except ValueError as e:
    print("Invalid broadcasting error:", e)


2D Array A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D Array B:
 [10 20 30]
A + B (Broadcasting result):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Shape of A: (3, 3) Shape of B: (3,) Shape of Result: (3, 3)
3D Array X:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
X + scalar (5):
 [[[ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]]]
Shape of X: (2, 2, 3) Shape of scalar: () Result Shape: (2, 2, 3)
Array D: [1 2] Shape: (2,)
Reshaped D:
 [[1]
 [2]] Shape: (2, 1)
Array E:
 [[10 20 30]
 [40 50 60]] Shape: (2, 3)
Broadcasted (D reshaped + E):
 [[11 21 31]
 [42 52 62]]
Shapes: D_reshaped: (2, 1) E: (2, 3) Result: (2, 3)
Invalid broadcasting error: operands could not be broadcast together with shapes (3,3) (4,) 
